spring:
  config:
    import: optional:.env[.properties]
  frontend:
    url: ${FRONT_END_URL}
  auth0:
    domain: ${AUTH0_DOMAIN}
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_USER_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUERURI}
auth0:
  audience: ${AUTH0_AUDIENCE}
