name: JUnit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: "actions/checkout@v3"

      - name: Set up JDK 17
        uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Run JUnit Tests
        working-directory: ./JobJournal
        run: mvn --batch-mode --update-snapshots package && mvn test
